version: '3'
services:
    app:
        build: ./.docker/php
        networks:
            - backend-net
        working_dir: /var/www/html
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html:cached
            - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        depends_on:
            - db
            - redis
    db:
        image: mysql:8
        ports:
            - "3311:3306"
        volumes:
            - 'db-mysql:/var/lib/mysql'
        networks:
            - backend-net
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1

    redis:
        image: 'redis:alpine'
        ports:
            - '6383:6379'
        volumes:
            - 'db-redis:/data'
        networks:
            - backend-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
            - backend-net

networks:
    backend-net:
        driver: bridge
volumes:
    db-mysql:
        driver: local
    db-redis:
        driver: local
